function [Zuser]=movie_test(isubset,isubsett,xranges,xrangest, ...
                            xmovies,xmoviest,glm_model, ...
                            Y0,xalpha, xalpha1,xalpha2,xalpha3, xalpha4, whichOption, ifold)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% select the potential test method
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% inputs:
%       isubset         training indeces
%       isubsett        test indeces
%       xranges         user index ranges in xdata for training
%       xrangest        user index ranges in xdata for test
%       xmovies         movie features for training
%       xmoviest        movie features for test
%       glm_model       total, user and movie averages
%       Y0              possible rankes
%       xalpha          dual variables
% outputs:
%       Zuser           user wise prediction for the test rankes      
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  itest_method = 0;   % =0 orig =1 Marlin type =2 Marlin merge 
  switch itest_method
    case 0      % matrix completition test
     [Zuser] = movie_test_orig(isubset, ...
                               isubsett, ...
                               xranges, ...
                               xrangest, ...
                               xmovies, ...
                               xmoviest, ...
                               glm_model, ...
                               Y0, ...
                               xalpha, ...
                               xalpha1,...
                               xalpha2, ...
                               xalpha3, ...
                               xalpha4, ...
                               whichOption, ...
                               ifold);
                           
% these are under construction     
    case 1
     [Zuser] = movie_test_marlin(isubset,isubsett,xranges,xrangest, ...
                            xmovies,xmoviest,glm_model, ...
                            Y0,xalpha);
    case 2
     [Zuser] = movie_test_marlin_merge(isubset,isubsett,xranges,xrangest, ...
                            xmovies,xmoviest,glm_model, ...
                            Y0,xalpha);
    case 3
     [Zuser] = movie_test_local(isubset,isubsett,xranges,xrangest, ...
                            xmovies,xmoviest,glm_model, ...
                            Y0,xalpha);
  end
  
  
  
